server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index konekta-inscricao.html;

    # Página Principal (Inscrição)
    location / {
        try_files $uri $uri/ /konekta-inscricao.html;
    }

    # Painel de Leads
    location = /leads {
        try_files /konekta-leads.html =404;
    }

    # Modelos de Teste
    location /t2 {
        try_files /konekta-landing-2.html =404;
    }
    location /t3 {
        try_files /konekta-landing-3-azul.html =404;
    }
    location /t4 {
        try_files /konekta-landing-4.html =404;
    }
    location /t5 {
        try_files /konekta-landing-5.html =404;
    }
    location /t6 {
        try_files /konekta-landing-6.html =404;
    }

    # Estáticos e outros arquivos
    location / {
        try_files $uri $uri/ =404;
    }

    # Erro 404 redireciona para a home
    error_page 404 /;
}
