server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /leads {
        try_files /konekta-leads.html =404;
    }

    # Links curtos para testes
    location /t2 { try_files /konekta-landing-2.html =404; }
    location /t3 { try_files /konekta-landing-3-azul.html =404; }
    location /t4 { try_files /konekta-landing-4.html =404; }
    location /t5 { try_files /konekta-landing-5.html =404; }
    location /t6 { try_files /konekta-landing-6.html =404; }

    error_page 404 /index.html;
}
